bring Emacs support closer to recent vs.code changes
dracula/emacs pull request #28
Opened 2017-06-10 10:42 UTC by CarstenKoenig

added some missing font-lock faces, overrode operators for Haskell-mode

> If you're fixing a UI issue, make sure you take two screenshots. One that shows the actual bug and another that shows how you fixed it.

2017-06-10 10:43 UTC, CarstenKoenig commented
this is related to some of the issues described here: https://github.com/dracula/emacs/issues/27

2017-06-28 18:01 UTC, film42 commented
@CarstenKoenig Are the screenshots in the issue before/ after? If not, would you mind posting a before/ after here in this PR so we can get a visual diff of the changes? Thanks ❤️ !

2017-06-28 18:09 UTC, CarstenKoenig commented
@film42 well not exactly the first one is vs.code the next one the current dracula version - the problem is that I tweaked the settings a bit more but I will try to reset them - basically it's mostly the operators that are colored too - I think you cannot adapt the **language pragmas** without changing *haskell-mode* too as those are all parsed into the same face

for a first preview here is the old one:
![draculabefore](https://user-images.githubusercontent.com/1927108/27652895-a72865c0-5c3d-11e7-9634-487ba45b8d47.png)

and this is the one I am using now:
![draculacurrent](https://user-images.githubusercontent.com/1927108/27652907-ae22528c-5c3d-11e7-9cac-eb9fc4a5aec7.png)

the main difference to the one in the pull request should be that I now use *pale green* for the type face

2018-04-16 05:38 UTC, zenorocha commented
@film42 can you take a look? Should we move this forward?

2018-04-16 13:53 UTC, film42 requested changes
Looking god. One small request and this will be good to go.

2018-04-16 13:53 UTC, film42 commented on dracula-theme.el
> +   `(font-lock-type-face ((,class (:foreground , "#00ffff"))))
Let's give this color a name in the list at the top of this file and this should be good to go.

2019-10-22 20:18 UTC, milouse commented
Fixed by 622806d5aca9b5e368d1ca44a789827e8c548017 and 526ba3df271740e72e5aa7da591f4bf9a2ca1643

Thank you for contributing

2019-10-22 20:18 UTC, closed without merging